services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: 'http app:8080'
    ports:
      - 4040:4040
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
